name: "SmedresmanLaw"
permalink: pretty
author: Theron Studios
url: http://smedresmanlaw.com/

gems:
  - jekyll-assets
  - uglifier
  - sass

exclude: ["CNAME","editorconfig.txt","Gemfile","Gemfile.lock","README.md", "RAKEFILE"]

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/pdf
  js_compressor: uglifier
  css_compressor: sass
